//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saan_market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int userId { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public short plaque { get; set; }
        public short floor { get; set; }
    
        public virtual User User { get; set; }
    }
}
